name: Download And Upload boot.img

on:
  workflow_dispatch:
    inputs:
      Download_Link:
        description: '下载链接'
        required: true

jobs:
  Download:
    runs-on: ubuntu-latest
    steps:
      - name: Download
        run: |
          wget ${{ github.event.inputs.Download_Link }}
      - name: Unzip
        shell: python
        run: |
          import zipfile,os
          if '${{ github.event.inputs.Download_Link }}'.endswith('zip'):
              for i,j,k in os.walk('./'):
                  for file in k:
                      if file.endswith('.zip'):
                          file=file
              f = zipfile.ZipFile(file,'r')
              if 'payload.bin' in f.namelist():
                  print('Download payload dumper')
                  os.system('git clone https://github.com/vm03/payload_dumper.git')
                  f.extract('payload.bin',"./payload_dumper/")
                  os.system('cd payload_dumper && pip3 install -r requirements.txt')
                  os.system('cd payload_dumper && python3 payload_dumper.py payload.bin')
                  os.system('mkdir output && cp payload_dumper/output/boot.img ./output/ && cp payload_dumper/output/init_boot.img ./output/')
          else:
              for i,j,k in os.walk('./'):
                  for file in k:
                      if file.endswith('.tgz'):
                          file=file
              os.system(f'tar -zxvf {file}')
              pathlist=[]
              for i,j,k in os.walk('./'):
                  for file in k:
                      if file=='boot.img' or file=='init_boot.img':
                          pathlist.append(os.path.join(i,file))
              os.system(f'mkdir output')
              for path in pathlist:
                  os.system(f'cp {path} output/')

      - name: Upload To Github Actions Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Download
          path: output
